server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/tomasmaiorino/config-repo.git
          repos:
            send-email:
              pattern: send-email*/local, send-email*/container
              uri: file:///Users/tomas.maiorino/Documents/personal/project/config-repo
