server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/tomas.maiorino/Documents/personal/project/config-repo
